services:
#    korobochkin_coppermine_gallery_parser.example:
#        class: Korobochkin\CoppermineGalleryParserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  guzzle:
    class: GuzzleHttp\Client

  coppermine_parser.parser:
    class: Korobochkin\CoppermineGalleryParserBundle\Service\Parser
    arguments: [ @guzzle, @logger ]